### ISSUE TITLE
Conflicting license information

### ISSUE THREAD

**Issue by TamsynUlthara** [hudora/huBarcode#19]
This package has conflicting license information.

On one hand, the `README` file states the following:

```
The code is available under the Apache License, Version 2.0.
```

On the other, the `setup.py` file contains the following:

```
'License :: OSI Approved :: BSD License',
```

And the `README` also contains this:

```
If you worry about copyright you might consider this Software BSD-Licensed.
If you are still worried, you might consider it GPL1/2/3 compatible.
```

If this package is Apache 2.0 licensed, this is incorrect; the Apache 2.0 license is _not_ compatible with versions of the GPL before v3.

I'd recommend picking a single license, placing the license text in a `LICENSE` file, and changing all references in the `README`, `setup.py`, and elsewhere to match.

**Comment by mdornseif** [comment]
So this code is

a) available under the Apache License, Version 2.0.
b) available under a BSD-Licensed
c) can be used with GPL software, since the author explicitly allows that

In german law - which is the on relevant to me - there is no need of a "license". So I don't really see the need to support a legal concept foreign to me.

**Comment by TamsynUlthara** [comment]
I'm assuming (and hoping!) you care about your users, since you took the time to release huBarcode on GitHub.  (And thank you for that!)  You may not care about licenses or whether your package is open source, but your users do!  In much of the world, they can't use your code without a license (or a public domain dedication).

**First**, there is no single "BSD license".  One sort of BSD license is not compatible with any version of the GPL (the BSD license with the "advertising clause").

**Second**, _you don't get to say_ whether your software is GPL-compatible, except by your choice of license.  It's the GPL software's author who would need to add an exception clause, not you.  Right now:
- If huBarcode is available only under the 4-clause BSD license, it is _not_ compatible with _any_ version of the GPL.
- If huBarcode is available only under the 3-clause or 2-clause BSD license, it _is_ compatible with _all_ versions of the GPL.
- If huBarcode is available only under the Apache 2.0 license, it is compatible _only_ with the GPLv3, and not previous versions (like the GPLv2).
- If huBarcode is available under the user's choice of one or more licenses, it depends on exactly what those choices are.

You cannot simply say you "explicitly allow" your software to be used with the GPL; it doesn't work that way.

Of course, it sounds like you _are_ saying that huBarcode has a license.  I'm only asking that you clarify which license it is, or explicitly state that it's available under the user's choice of one or more licenses.

If you are claiming that your package is available under the user's choice of either the (3-clause or 2-clause) BSD license or the Apache 2.0 license, please say _exactly that_ somewhere like the README, and if you don't want to place a LICENSE file, at least link to the license text somewhere else, so users know exactly what the terms are.  Right now the README text is a combination of unclear and incorrect.

I'd be happy to send a pull request with the appropriate changes if you permit them, so you don't even have to do the work.

Thank you.  :-)

**Comment by mdornseif** [comment]
Thank you for your feedback and your interpretation of international license and software ownership law. Since I hold a Phd in laws please allow me my own interpretation of these matters.

Generally I understand that many software developers struggle with legal issues and try to read legal situations like code but law is not black or white.

Obviously I can state that my software may be used with GPL software. The question is if GPL software can be used with my software.

Generally my software is meant for people enjoying programming and the beauty of code. If you are into the need of knowing exactly what the legal situation - spanning at least three continents - with that code is, the code might not be for you.

**Comment by TamsynUlthara** [comment]
I give up. I care more about the enjoyment and elegance of code more than most programmers — but in the real world, where programmers actually _get things done_, the legal status of code actually _matters_.

You're presenting a straw man: no practical developer is asking to know _exactly_ what the legal interpretation of, e.g., the BSD license is in a given venue of law, but the popular open-source licenses have been vetted by many lawyers, and developers have learned to trust those licenses. Your "license", on the other hand, has only one person's weight behind it, PhD or not.

I even offered to do all the work of assembling a patch if you'd simply pick a license. You've made it glaringly obvious, though, that you care more about snark and playing semantic games than addressing the needs of your users.  That's a shame. I hope you'll change your mind someday, but I won't hold my breath.
